### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Ticki** [Kingdread/Rurtle#2]
Due to changes in glium, rurtle does not compile

**Comment by Kingdread** [comment]
Thanks for reporting, I will look into this (and hopefully fix it)! :smile:

**Comment by Kingdread** [comment]
Should be fixed with 62e1d03bff1674b316edf0fa0f6675b965d9ef25 though compilation still fails because of tomaka/glium_text#13, but you can get around that by using a local version of `glium_text` that has the fix mentioned in the issue applied.

**Comment by Kingdread** [comment]
It looks like `glium_text` compiles again, so I'm closing this for now.
